version: "3.8"

services:

    app:
        container_name: gitclub
        image: gitclub
        ports:
            - "5000:5000"
        depends_on:
            - db
        env_file:
            - .env
        environment:
            DB_HOST: db
