version: "3.8"

services:

    db:
        container_name: db
        image: postgres:alpine
        ports:
            - "${DB_PORT}:5432"
        environment:
            POSTGRES_DB: $DB_NAME
            POSTGRES_PASSWORD: $DB_PASSWORD

    redis:
        container_name: redis
        image: redis:latest
        init: true
        ports:
            - ${REDIS_PORT-6379}:6379
